service.info:
  name: Restful API Service
  version: 1.0.0

error.path: /errorPage
server.error.includeStacktrace: ON_TRACE_PARAM

spring.jpa.show-sql: true

handlebars:
  prefix: "classpath:templates/"
  registerMessageHelper: true
  failOnMissingFile: false

logging.level.org.ksug: WARN
logging.level.org.springframework: INFO
logging.level.org.springframework.transaction: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.boot: DEBUG